version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "8000:80"
      - "5173:5173"  # Port Vite
    depends_on:
      - db
    volumes:
      - ./app:/var/www
      - /var/www/node_modules  # Unikamy problemów z node_modules
    restart: unless-stopped
    networks:
    - backend

  # Serwis Users
  users:
    build:
      context: ./users
    container_name: users
    ports:
      - "8001:80"
      - "5174:5174"  # Port Vite
    depends_on:
      - db
    volumes:
      - ./users:/var/www
      - /var/www/node_modules  # Unikamy problemów z node_modules
    restart: unless-stopped
    networks:
      - backend

  # Serwis Events
  events:
    build:
      context: ./events
    container_name: events
    ports:
      - "8002:80"
      - "5175:5175"  # Port Vite
    depends_on:
      - db
    volumes:
      - ./events:/var/www
      - /var/www/node_modules  # Unikamy problemów z node_modules
    restart: unless-stopped
    networks:
      - backend

      # Serwis Events
  bookings:
    build:
      context: ./bookings
    container_name: bookings
    ports:
      - "8003:80"
      - "5176:5176"  # Port Vite
    depends_on:
      - db
    volumes:
      - ./bookings:/var/www
      - /var/www/node_modules  # Unikamy problemów z node_modules
    restart: unless-stopped
    networks:
      - backend

  # Baza danych MySQL
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local
