[supervisord]
nodaemon=true

[program:apache2]
command=apache2-foreground
autostart=true
autorestart=true
priority=1

[program:vite]
command=npm run dev
directory=/var/www
autostart=true
autorestart=true
priority=2
startretries=3
startsecs=5
